name: astro-page-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  astro-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    - name: Archive build output
      run: "tar --dereference --directory dist/ -cvf artifact.tar ."
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: github-pages
        path: artifact.tar
  deploy:
    # Required: Pages permissions for deploying
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: astro-build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy artifact
        id: deployment
        uses: paper-spa/deploy-pages@main
        with:
          # Deploy Pull Request builds to a preview site
          preview: ${{ github.event_name == 'pull_request' }}
