name: astro-page-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  pull_request_target:

jobs:
  astro-build:
    permissions:
      # Only allow read token for building
      contents: read
    runs-on: ubuntu-latest

    steps:
      #
      # Separate PR checkout when event is pull_request_target
      #
    - name: Checkout PR
      if: ${{ github.event_name == 'pull_request_target' }}
      uses: actions/checkout@v2
      with:
        # For PRs make sure to checkout the PR branch
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}

      #
      # Normal checkout without forks
      #
    - name: Checkout
      if: ${{ github.event_name != 'pull_request_target' }}
      uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    - name: Archive build output
      run: "tar --dereference --directory dist/ -cvf artifact.tar ."
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: github-pages
        path: artifact.tar
  deploy:
    # Required: Pages permissions for deploying
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: astro-build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy artifact
        id: deployment
        uses: paper-spa/deploy-pages@main
        with:
          # Deploy Pull Request builds to a preview site
          preview: ${{ github.event_name == 'pull_request_target' }}
