name: astro-page-build

on:
  push:
    branches: [ main ]
  pull_request_target:
  merge_group:

jobs:
  astro-build:
    permissions:
      # Only allow read token for building
      contents: read
    runs-on: ubuntu-latest

    steps:
      #
      # Separate PR checkout when event is pull_request_target
      #
    - name: Checkout PR
      if: ${{ github.event_name == 'pull_request_target' }}
      uses: actions/checkout@v4
      with:
        # For PRs make sure to checkout the PR branch
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}

      #
      # Normal checkout without forks
      #
    - name: Checkout
      if: ${{ github.event_name != 'pull_request_target' }}
      uses: actions/checkout@v4

    - name: Pre Deployment Verification
      run: |
        # Get the current deployed commit SHA
        CURRENT_SHA=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/deployments?environment=github-pages" \
          | jq -r '.[0].sha')

        # Get the head commit SHA for the ref
        HEAD_SHA=$(git rev-parse HEAD)

        # Compare the commit timestamps
        if [[ $(git show -s --format=%ct $CURRENT_SHA) -gt $(git show -s --format=%ct $HEAD_SHA) ]]; then
          echo "The head SHA for the ref is older than the one currently deployed."
        else
          echo "The head SHA for the ref ($HEAD_SHA) is newer or the same as the one currently deployed ($CURRENT_SHA)."
          echo "::error::The head SHA for the ref ($HEAD_SHA) is newer or the same as the one currently deployed ($CURRENT_SHA)."
          exit 1
        fi


    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    - name: Archive build output
      run: "tar --dereference --directory dist/ -cvf artifact.tar ."
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: github-pages
        path: artifact.tar
  deploy:
    # Required: Pages permissions for deploying
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: astro-build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v3
        with:
          # Deploy Pull Request builds to a preview site
          preview: ${{ github.event_name == 'pull_request_target' }}
